// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmyqrfbghesbhnfphdlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBteXFyZmJnaGVzYmhuZnBoZGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4Njk4NjAsImV4cCI6MjA1NjQ0NTg2MH0.3WLa7lAsO_hJy_ck9zbRFTFMMzr-hiiE5W4P_2yVWkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);